/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controler.ControlerChair;
import controler.ControlerFunction;
import controler.ControlerLivingRoom;
import controler.ControlerMovie;
import controler.ControlerTicket;
import controler.ControlerUser;
import java.awt.Image;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.util.LinkedList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Chair;
import model.Function;
import model.Movie;
import model.Ticket;
import model.User;
import service.Service;

/**
 *
 * @author sergi
 */
public class Prueba extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    ControlerMovie controlerMovie;
    ControlerUser controlerUser;
    ControlerChair controlerChair;
    ControlerFunction controlerFunction;
    ControlerTicket controlerTickets;

    public Prueba() {
        initComponents();
        this.setSize(1300, 670);
        Setimagas();
        String urlServer = "http://localhost:8080/";
        Service service = new Service(urlServer);
        this.controlerMovie = new ControlerMovie(service);
        this.controlerUser = new ControlerUser(service);
        this.controlerChair = new ControlerChair(service);
        this.controlerFunction = new ControlerFunction(service);
        this.controlerTickets = new ControlerTicket(service);
        toList();


    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPaneTicket = new javax.swing.JTabbedPane();
        jPanelUsers = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnUsersSearch = new javax.swing.JButton();
        btnUsersCreate = new javax.swing.JButton();
        btnUsersUpdate = new javax.swing.JButton();
        btnUsersDelete = new javax.swing.JButton();
        btnUsersTolist = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUserIdUser = new javax.swing.JTextField();
        txtUserNameUser = new javax.swing.JTextField();
        txtUserIdentUser = new javax.swing.JTextField();
        txtUserBirthDatUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblUsers = new javax.swing.JLabel();
        jPanelTicket = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTicketCreate = new javax.swing.JButton();
        btnTicketUpdate = new javax.swing.JButton();
        fondo2Ticket = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtPay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblFunction = new javax.swing.JTable();
        lblUserId = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblchair = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        comboTickets = new javax.swing.JComboBox<>();
        comboUsers = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblFondoTicket = new javax.swing.JLabel();
        jPanelMovie = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMovie = new javax.swing.JTable();
        btnMovieToList = new javax.swing.JButton();
        btnMovieCreate = new javax.swing.JButton();
        btnMovieSearch = new javax.swing.JButton();
        btnMovieUpdate = new javax.swing.JButton();
        btnMovieDelete = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtNameMovie = new javax.swing.JTextField();
        txtYearMovie = new javax.swing.JTextField();
        boxTypeMovie = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        txtMovieID = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        lblFondoMovie = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTickets = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblInfo = new javax.swing.JLabel();
        lblFondoTicketInfo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 670));
        setSize(new java.awt.Dimension(1300, 670));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1300, 800));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelUsers.setPreferredSize(new java.awt.Dimension(900, 429));
        jPanelUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("To list");
        jPanelUsers.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 460, 120, 30));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        jPanelUsers.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 470, 380));

        btnUsersSearch.setText("jButton1");
        btnUsersSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersSearchActionPerformed(evt);
            }
        });
        jPanelUsers.add(btnUsersSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 90, 80));

        btnUsersCreate.setText("jButton1");
        btnUsersCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersCreateActionPerformed(evt);
            }
        });
        jPanelUsers.add(btnUsersCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 100, 80));

        btnUsersUpdate.setText("jButton2");
        btnUsersUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersUpdateActionPerformed(evt);
            }
        });
        jPanelUsers.add(btnUsersUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 100, 80));

        btnUsersDelete.setText("jButton3");
        btnUsersDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersDeleteActionPerformed(evt);
            }
        });
        jPanelUsers.add(btnUsersDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 100, 80));

        btnUsersTolist.setText("jButton1");
        jPanelUsers.add(btnUsersTolist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 500, 100, 80));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setText("Search");
        jPanelUsers.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 120, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setText("Create");
        jPanelUsers.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 120, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setText("Update");
        jPanelUsers.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 120, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel15.setText("Delete");
        jPanelUsers.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 120, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("User Id:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("name:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("inent:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setText("Birth of date:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 30));
        jPanel1.add(txtUserIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 170, -1));
        jPanel1.add(txtUserNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 170, -1));
        jPanel1.add(txtUserIdentUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 170, -1));
        jPanel1.add(txtUserBirthDatUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, -1));

        jPanelUsers.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 350, 210));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        jLabel2.setText("User");
        jPanelUsers.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));
        jPanelUsers.add(lblUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 670));

        jTabbedPaneTicket.addTab("Users", jPanelUsers);

        jPanelTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        jLabel1.setText("Ticket");
        jPanelTicket.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 90, -1));

        btnTicketCreate.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnTicketCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketCreateActionPerformed(evt);
            }
        });
        jPanelTicket.add(btnTicketCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 120, 80));

        btnTicketUpdate.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnTicketUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketUpdateActionPerformed(evt);
            }
        });
        jPanelTicket.add(btnTicketUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 110, 80));

        fondo2Ticket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fondo2Ticket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Type:");
        fondo2Ticket.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 30));
        fondo2Ticket.add(txtPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 220, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Pay value:");
        fondo2Ticket.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 30));

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adult", "Children" }));
        fondo2Ticket.add(comboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Ticket information");
        fondo2Ticket.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanelTicket.add(fondo2Ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 340, 200));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setText("Choose a function");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        tblFunction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblFunction);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 360, 200));

        jPanelTicket.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 480, 260));

        lblUserId.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblUserId.setText("User Identification:");
        jPanelTicket.add(lblUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 170, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel18.setText("Choose a chair");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        tblchair.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblchair);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 300, 160));

        jPanelTicket.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 340, 250));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel25.setText("Create");
        jPanelTicket.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, -1, -1));

        comboTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTicketsActionPerformed(evt);
            }
        });
        jPanelTicket.add(comboTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, -1));

        comboUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUsersActionPerformed(evt);
            }
        });
        jPanelTicket.add(comboUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 110, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel23.setText("Select an id ticket for update it");
        jPanelTicket.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel24.setText("Update");
        jPanelTicket.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, -1, -1));

        lblFondoTicket.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanelTicket.add(lblFondoTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 40, 1300, 670));

        jTabbedPaneTicket.addTab("Tickets", jPanelTicket);

        jPanelMovie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        lblTitulo.setText("Movie");
        jPanelMovie.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 90, 50));

        tblMovie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblMovie);

        jPanelMovie.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 470, 320));

        btnMovieToList.setText("jButton1");
        btnMovieToList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieToListActionPerformed(evt);
            }
        });
        jPanelMovie.add(btnMovieToList, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 90, 70));

        btnMovieCreate.setText("jButton1");
        btnMovieCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieCreateActionPerformed(evt);
            }
        });
        jPanelMovie.add(btnMovieCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 90, 70));

        btnMovieSearch.setText("jButton1");
        btnMovieSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieSearchActionPerformed(evt);
            }
        });
        jPanelMovie.add(btnMovieSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 90, 70));

        btnMovieUpdate.setText("jButton1");
        btnMovieUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieUpdateActionPerformed(evt);
            }
        });
        jPanelMovie.add(btnMovieUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 90, 70));

        btnMovieDelete.setText("jButton1");
        btnMovieDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieDeleteActionPerformed(evt);
            }
        });
        jPanelMovie.add(btnMovieDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 90, 70));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel27.setText("To list");
        jPanelMovie.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel26.setText("Year:");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel29.setText("Movie ID:");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel30.setText("Type:");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel4.add(txtNameMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 190, -1));
        jPanel4.add(txtYearMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 190, -1));

        boxTypeMovie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Science fiction", "comedy", "action", "adventure", "drama", "love", "fancy", "musical", "documentary", "film", "childish" }));
        jPanel4.add(boxTypeMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel33.setText("Name:");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel4.add(txtMovieID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 190, -1));

        jPanelMovie.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 320, 260));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel28.setText("Search");
        jPanelMovie.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel31.setText("Create");
        jPanelMovie.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel32.setText("Update");
        jPanelMovie.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        Delete.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Delete.setText("Delete");
        jPanelMovie.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        lblFondoMovie.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanelMovie.add(lblFondoMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1300, 670));

        jTabbedPaneTicket.addTab("Movies", jPanelMovie);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(tblTickets);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 700, 300));

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, -1, -1));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, -1, -1));
        jPanel5.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 160, 20));
        jPanel5.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 1230, 120));

        lblFondoTicketInfo.setText("jLabel16");
        jPanel5.add(lblFondoTicketInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 670));

        jLabel17.setText("(Insert Id)");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, -1, -1));

        jLabel19.setText("select item from de table to delete it ");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, -1, -1));

        jTabbedPaneTicket.addTab("Tickets Information", jPanel5);

        jDesktopPane1.add(jTabbedPaneTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsersCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersCreateActionPerformed
        // TODO add your handling code here:
        if (txtUserBirthDatUser.getText().equals("") || txtUserIdentUser.getText().equals("") || txtUserNameUser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor llene tdos los campos");

        } else {
            User user = new User(txtUserNameUser.getText(), txtUserIdentUser.getText(), txtUserBirthDatUser.getText());
            controlerUser.create(user);
            tableUserUpdate(controlerUser.toList());
        }
        borrarFormUser();
    }//GEN-LAST:event_btnUsersCreateActionPerformed


    private void btnUsersUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersUpdateActionPerformed
        // TODO add your handling code here:
        if (txtUserBirthDatUser.getText().equals("") || txtUserIdentUser.getText().equals("")
                || txtUserNameUser.getText().equals("") || txtUserIdUser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Press search by id");
        } else {
            String name = txtUserNameUser.getText();
            String ident = txtUserIdentUser.getText();
            String BirthOfDate = txtUserBirthDatUser.getText();
            User user = new User(name, ident, BirthOfDate);
            user.setId(txtUserIdUser.getText());
            controlerUser.update(user);
            tableUserUpdate(controlerUser.toList());
        }
        borrarFormUser();
    }//GEN-LAST:event_btnUsersUpdateActionPerformed

    private void btnUsersDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersDeleteActionPerformed
        // TODO add your handling code here:
        if (txtUserIdUser.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "llene el campo id");
        } else {
            User user = new User();
            user.setId(txtUserIdUser.getText());
            controlerUser.delete(user);
            tableUserUpdate(controlerUser.toList());
            borrarFormUser();
        }
    }//GEN-LAST:event_btnUsersDeleteActionPerformed

    private void btnTicketUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketUpdateActionPerformed
       if(this.comboTickets.getSelectedIndex() != -1){
         if (!this.txtPay.getText().equals("")){
            String id  = (String)this.comboTickets.getSelectedItem();
            double value = parseDouble(this.txtPay.getText());
            String type = (String)this.comboType.getSelectedItem();
            Function function = this.controlerFunction.toList().get(this.tblFunction.getSelectedRow());
            Chair chair = this.controlerChair.toList().get(this.tblchair.getSelectedRow());
            User user = this.controlerUser.toList().get(comboUsers.getSelectedIndex());
            Ticket ticket = new Ticket(id, value, type);
            ticket.setFunction(function);
            ticket.setChair(chair);
            ticket.setUser(user);
            this.controlerTickets.update(ticket);
            
            this.tableTicketUpdate(this.controlerTickets.toList());
        
         }else{
             JOptionPane.showMessageDialog(rootPane, "fill all the gaps");
         }
       } else {
            JOptionPane.showMessageDialog(rootPane, "select an id ticket");
       }
    }//GEN-LAST:event_btnTicketUpdateActionPerformed

    private void btnMovieCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieCreateActionPerformed
        // TODO add your handling code here:
        if (txtNameMovie.getText().equals("") || txtYearMovie.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "por favor llene todos los campos");
        } else {
            Movie movie = new Movie(txtNameMovie.getText(), Integer.parseInt(txtYearMovie.getText()), boxTypeMovie.getSelectedItem().toString());
            this.controlerMovie.create(movie);
            tableMovieUpdate(this.controlerMovie.toList());
        }
        borrarFormMovie();
    }//GEN-LAST:event_btnMovieCreateActionPerformed

    private void btnMovieSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieSearchActionPerformed
        // TODO add your handling code here:
        if (txtMovieID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "debe insertar el codigo");
        } else {

            Movie movie;

            movie = this.controlerMovie.watch(this.txtMovieID.getText());
            if (movie != null) {
                this.txtNameMovie.setText(movie.getName());
                this.txtYearMovie.setText(movie.getYear() + "");
                System.out.println(searchYear(movie));
                this.boxTypeMovie.setSelectedIndex(searchYear(movie));
                this.txtNameMovie.setText(movie.getName());

            } else {
                JOptionPane.showMessageDialog(null, "Username does not exist");
            }

        }

        //borrarFormMovie();
    }//GEN-LAST:event_btnMovieSearchActionPerformed


    private void btnMovieToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieToListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMovieToListActionPerformed

    private void btnUsersSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersSearchActionPerformed
        if (txtUserIdUser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "debe insertar el codigo");
        } else {
            User user = this.controlerUser.watch(this.txtUserIdUser.getText());
            if (user != null) {
                this.txtUserIdentUser.setText(user.getIdent());
                this.txtUserNameUser.setText(user.getName());
                this.txtUserBirthDatUser.setText(user.getBirthDate());
            } else {
                JOptionPane.showMessageDialog(null, "Username does not exist");
            }
        }
    }//GEN-LAST:event_btnUsersSearchActionPerformed

    private void btnMovieUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieUpdateActionPerformed
        // TODO add your handling code here:
        if (txtMovieID.getText().equals("") || txtNameMovie.getText().equals("") || txtYearMovie.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Press search by id");
        } else {
            String name = txtNameMovie.getText();
            int year = Integer.parseInt(txtYearMovie.getText());
            String type = boxTypeMovie.getSelectedItem().toString();
            Movie movie = new Movie(name, year, type);
            movie.setId(txtMovieID.getText());
            this.controlerMovie.update(movie);
            tableMovieUpdate(this.controlerMovie.toList());
        }
        borrarFormMovie();
    }//GEN-LAST:event_btnMovieUpdateActionPerformed

    private void btnMovieDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieDeleteActionPerformed
        // TODO add your handling code here:
        if (txtMovieID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "por favor inserte el id a ser eliminado");
        } else {

            Movie movie = new Movie();
            movie.setId(txtMovieID.getText());
            this.controlerMovie.delete(movie);
            tableMovieUpdate(this.controlerMovie.toList());
            borrarFormMovie();
        }
    }//GEN-LAST:event_btnMovieDeleteActionPerformed

    private void btnTicketCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketCreateActionPerformed
      if (this.comboUsers.getSelectedIndex() != -1 &&this.tblchair.getSelectedRow() != -1 && this.tblFunction.getSelectedRow() != -1 && !"".equals(this.txtPay.getText())  ){
          Ticket ticket = new Ticket(Double.parseDouble(this.txtPay.getText()), this.comboType.getItemAt(this.comboType.getSelectedIndex()));
          Function function = this.controlerFunction.toList().get(tblFunction.getSelectedRow());
          Chair chair = this.controlerChair.toList().get(this.tblchair.getSelectedRow());
          User user = this.controlerUser.toList().get(this.comboUsers.getSelectedIndex());
    
          ticket.setFunction(function);
          ticket.setChair(chair);
          ticket.setUser(user);
            user.setTicket(ticket);
        
          if (this.controlerTickets.create(ticket)){
               JOptionPane.showMessageDialog(this, "creation succesfully");
           tableTicketUpdate(this.controlerTickets.toList());
              this.tableUserUpdate(this.controlerUser.toList());
           this.txtPay.setText("");
           showTickets();
          }
          
         
      } else{
          JOptionPane.showMessageDialog(this, "fill all the gaps");
      }
    }//GEN-LAST:event_btnTicketCreateActionPerformed

    private void comboUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUsersActionPerformed

    private void comboTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTicketsActionPerformed
       //this.controlerTickets.toList();
    }//GEN-LAST:event_comboTicketsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if (!txtId.getText().equals("")){
          Ticket ticket= this.controlerTickets.watch(txtId.getText());
          this.lblInfo.setText("id: "+ticket.getId()+"\n"+
                   "Type: "+ ticket.getType()+"\n "+
                 "pay value: " + ticket.getPayValue() +"\n " + 
                   "Function: \n" +"    "+ticket.getFunction().getDate()+ "\n" +
                  "     "+ ticket.getFunction().getHour() + "\n"+
                  "     " + ticket.getFunction().getRefMovie().getName()+ "\n" +
                  "     "+ ticket.getFunction().getRefLivingRoom().getName() + "\\n"+
                  "Chair: "+"\n"+
                  ticket.getChair().getLetter()+" " +ticket.getChair().getNumber()+ "\n"+
                  "User: " + "\n"+ 
                  "     "+ ticket.getUser().getIdent()+ "\n"+
                  "     "+ ticket.getUser().getName()+ "\n"+
                  "     "+ ticket.getUser().getBirthDate());
      } else {
          JOptionPane.showMessageDialog(this, "you must insert an id ticket");
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (this.tblTickets.getSelectedRow() != -1){
            Ticket ticket =this.controlerTickets.toList().get(this.tblTickets.getSelectedRow());
            controlerTickets.delete(ticket);
            this.tableTicketUpdate(controlerTickets.toList());
           this.showTickets();
           
       } else {
           JOptionPane.showMessageDialog(rootPane, "you must select an item from de table ");
       }
          
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Setimagas() {
        btnTicketCreate.setIcon(SetIcon("/image/idea.png", btnTicketCreate));
        btnTicketUpdate.setIcon(SetIcon("/image/update.png", btnTicketUpdate));
        btnUsersUpdate.setIcon(SetIcon("/image/update.png", btnUsersUpdate));
        btnUsersCreate.setIcon(SetIcon("/image/idea.png", btnUsersCreate));
        btnUsersDelete.setIcon(SetIcon("/image/delete.png", btnUsersDelete));
        btnUsersSearch.setIcon(SetIcon("/image/search.png", btnUsersSearch));
        btnUsersTolist.setIcon(SetIcon("/image/prueba.png", btnUsersTolist));
        btnMovieCreate.setIcon(SetIcon("/image/idea.png", btnMovieCreate));
        btnMovieUpdate.setIcon(SetIcon("/image/update.png", btnMovieUpdate));
        btnMovieDelete.setIcon(SetIcon("/image/delete.png", btnMovieDelete));
        btnMovieToList.setIcon(SetIcon("/image/prueba.png", btnMovieToList));
        btnMovieSearch.setIcon(SetIcon("/image/search.png", btnMovieSearch));
        btnMovieCreate.setIcon(SetIcon("/image/idea.png", btnMovieCreate));
        setImage(lblFondoTicket, "src/image/fondo.jpg");
        setImage(lblUsers, "src/image/fondo.jpg");
        setImage(lblFondoMovie, "src/image/fondo.jpg");
         setImage(this.lblFondoTicketInfo, "src/image/fondo.jpg");
    }

    public int searchYear(Movie movie) {
        int aux = -1;
        for (int i = 0; i < 12; i++) {
            if (movie.getType().equals(boxTypeMovie.getItemAt(i))) {
                aux = i;
            }
        }
        return aux;
    }

    private void setImage(JLabel label, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(label.getWidth(),
                        label.getHeight(),
                        Image.SCALE_DEFAULT
                )
        );
        label.setIcon(icon);
        this.repaint();

    }

    public void borrarFormMovie() {
        txtMovieID.setText("");
        txtNameMovie.setText("");
        txtYearMovie.setText("");
        boxTypeMovie.setSelectedIndex(0);
    }

    public void borrarFormUser() {
        txtUserBirthDatUser.setText("");
        txtUserIdUser.setText("");
        txtUserIdentUser.setText("");
        txtUserNameUser.setText("");
    }

    public Icon SetIcon(String url, JButton boton) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }

    public void tableUserUpdate(LinkedList<User> listUsers) {
        String columName[] = {"Id", "Name", "identification", "born date"};
        DefaultTableModel miModelo = new DefaultTableModel(null, columName);
        this.tblUsers.setModel(miModelo);

        for (User user : listUsers) {
            String fila[] = new String[columName.length];
            fila[0] = user.getId();
            fila[1] = user.getName();
            fila[2] = "" + user.getIdent();
            fila[3] = "" + user.getBirthDate();
            miModelo.addRow(fila);

        }

    }
   /* public void tableUserTicket(LinkedList<User> listUsers) {
        String columName[] = {"Id", "Name", "ticket", "identification", "birth of Date"};
        DefaultTableModel miModelo = new DefaultTableModel(null, columName);
        this.tblUserTicket.setModel(miModelo);

        for (User user : listUsers) {
            String fila[] = new String[columName.length];
            fila[0] = user.getId();
            fila[1] = user.getName();
            fila[2] = "" + user.getTicket();
            fila[3] = "" + user.getIdent();
            fila[4] = "" + user.getBirthDate();
            miModelo.addRow(fila);

        }

    }
    
 */  
    public boolean checkNotTicket(User user) {
        boolean bandera = true;

        if (user.getTicket() != null) {
            bandera = false;
        }

        return bandera;
    }

    public void tableMovieUpdate(LinkedList<Movie> listMovies) {
        String columName[] = {"Id", "Name", "year", "type"};
        DefaultTableModel miModelo = new DefaultTableModel(null, columName);
        this.tblMovie.setModel(miModelo);
        for (Movie actual : listMovies) {
            String fila[] = new String[columName.length];
            fila[0] = actual.getId();
            fila[1] = actual.getName();
            fila[2] = "" + actual.getYear();
            fila[3] = "" + actual.getType();
            miModelo.addRow(fila);
        }

    }
    
    public void tableChairUpdate(LinkedList<Chair> chairList){
        String columName[] = {"id","letter", "number"};
        DefaultTableModel miModelo = new DefaultTableModel(null, columName);
        this.tblchair.setModel(miModelo);
        for (Chair chair :chairList ){
            String fila[] = new String [columName.length];
            fila [0] = chair.getId();
            fila [1] = ""+chair.getLetter();
            fila [2] = ""+chair.getNumber();
            miModelo.addRow(fila);
            
        }
        
    }
    
    public void tableFunctionUpdate(LinkedList <Function> functions){
                String columName[] = {"id", "hour","date", "movie", "room"};
        DefaultTableModel miModelo = new DefaultTableModel(null, columName);
        this.tblFunction.setModel(miModelo);
        for (Function function :functions ){
            String fila[] = new String [columName.length];
            fila [0] = function.getId();
            fila [1] = ""+function.getHour();
            fila [2] = ""+function.getDate();
            fila [3] = function.getRefMovie().getName();
            fila [4] = function.getRefLivingRoom().getName();
            miModelo.addRow(fila);
            
        }
        
    }
        public void tableTicketUpdate(LinkedList <Ticket> tickets){
                String columName[] = {"id","value", "type", "function","chair", "user"};
        DefaultTableModel miModelo = new DefaultTableModel(null, columName);
        this.tblTickets.setModel(miModelo);
        for (Ticket ticket :tickets ){
            String fila[] = new String [columName.length];
            fila [0] = ticket.getId();
            fila [1] = ""+ticket.getPayValue();
            fila [2] = ticket.getType();
            fila [3] = ticket.getFunction().getRefMovie().getName()+", "+ ticket.getFunction().getDate()+", "+ ticket.getFunction().getHour();
            fila [4] = ticket.getChair().getLetter()+", " + ticket.getChair().getNumber();
            fila [5] = ticket.getUser().getName();
            miModelo.addRow(fila);
            
        }
        
    }
    
    
    public void toList() {
        tableMovieUpdate(this.controlerMovie.toList());
        tableUserUpdate(controlerUser.toList());
        tableChairUpdate(this.controlerChair.toList());
        tableFunctionUpdate(this.controlerFunction.toList());
        System.out.println("this.controlerFunction.toList()");
        LinkedList <User> userList =this.controlerUser.toList();
        for (User user: userList){
             comboUsers.addItem(user.getIdent());
        }
      showTickets();
      //  tableUserTicket(controlerUser.toList());

    }
    
    public void showTickets(){
          LinkedList <Ticket> tickets = this.controlerTickets.toList();
          this.comboTickets.removeAll();
        for (Ticket ticket : tickets){
            
            this.comboTickets.addItem(ticket.getId());
        }
       this.tableTicketUpdate(tickets);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Delete;
    private javax.swing.JComboBox<String> boxTypeMovie;
    private javax.swing.JButton btnMovieCreate;
    private javax.swing.JButton btnMovieDelete;
    private javax.swing.JButton btnMovieSearch;
    private javax.swing.JButton btnMovieToList;
    private javax.swing.JButton btnMovieUpdate;
    private javax.swing.JButton btnTicketCreate;
    private javax.swing.JButton btnTicketUpdate;
    private javax.swing.JButton btnUsersCreate;
    private javax.swing.JButton btnUsersDelete;
    private javax.swing.JButton btnUsersSearch;
    private javax.swing.JButton btnUsersTolist;
    private javax.swing.JButton btnUsersUpdate;
    private javax.swing.JComboBox<String> comboTickets;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JComboBox<String> comboUsers;
    private javax.swing.JPanel fondo2Ticket;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelMovie;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JPanel jPanelUsers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPaneTicket;
    private javax.swing.JLabel lblFondoMovie;
    private javax.swing.JLabel lblFondoTicket;
    private javax.swing.JLabel lblFondoTicketInfo;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JTable tblFunction;
    private javax.swing.JTable tblMovie;
    private javax.swing.JTable tblTickets;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTable tblchair;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMovieID;
    private javax.swing.JTextField txtNameMovie;
    private javax.swing.JTextField txtPay;
    private javax.swing.JTextField txtUserBirthDatUser;
    private javax.swing.JTextField txtUserIdUser;
    private javax.swing.JTextField txtUserIdentUser;
    private javax.swing.JTextField txtUserNameUser;
    private javax.swing.JTextField txtYearMovie;
    // End of variables declaration//GEN-END:variables
}
